### PR TITLE
[GITHUB-7] Add sanity checks to release.sh

### PR DESCRIPTION
**Pull request by dennisconrad**
Add sanity checks to release.sh

- Ensure correct branch

- Ensure working tree is clean

- Ensure there are no un-pushed commits

- Ensure local branch is up to date

### CODE REVIEW

**Comment by tuxpower** [comment]
LGTM

**Comment by racer1680** [comment]
We do do bullet points now? :)

**Comment by lobsterdore** [comment]
Tested and it looks good, can you add '[GITHUB-7] ' to the beginning of the commit message?

**Comment by lobsterdore** [comment]
LGTM 👍

**Pull request merged**
